const PLAYLIST_DATA = [
  {
    name: "Guilt",
    author: "Nero",
    album: "Welcome Reality",
    time: "4:44",
    description: "",
    id: 1,
  },
  {
    name: "Elektro",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    time: "2:22",
    description: "",
    id: 2,
  },
  {
    name: "I’m Fire",
    author: "Ali Bakgor",
    album: "I’m Fire",
    time: "2:22",
    description: "",
    id: 3,
  },
  {
    name: "Non Stop",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    time: "4:12",
    description: "(Remix)",
    id: 4,
  },
  {
    name: "Run Run",
    author: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    time: "2:54",
    description: "(feat. AR/CO)",
    id: 5,
  },
  {
    name: "Eyes on Fire",
    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    time: "5:20",
    description: "(Zeds Dead Remix)",
    id: 6,
  },
  {
    name: "Mucho Bien",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    time: "3:41",
    description: "Hi Profile Remix",
    id: 7,
  },
  {
    name: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    description: "",
    id: 8,
  },
  {
    name: "How Deep Is Your Love",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    time: "3:32",
    description: "",
    id: 9,
  },
  {
    name: "Morena",
    author: "Tom Boxer",
    album: "Soundz Made in Romania",
    time: "3:36",
    description: "",
    id: 10,
  },
];

export default PLAYLIST_DATA;
